language: ruby
gemfile: test/Gemfile
before_install: cd test
script:
 - bin/rails db:environment:set RAILS_ENV=test
 - RAILS_ENV=test bundle exec rake db:drop
 - RAILS_ENV=test bundle exec rake db:migrate:status
 - RAILS_ENV=test bundle exec rake db:schema:cache:clear
 - RAILS_ENV=test bundle exec rake db:schema:load
 - RAILS_ENV=test bundle exec rake db:migrate:status
 - RAILS_ENV=test bundle exec rake db:schema:dump
 - RAILS_ENV=test bundle exec rake db:migrate
 - RAILS_ENV=test bundle exec rake db:migrate:status
 - RAILS_ENV=test bundle exec rake test
